import { useRef, useState } from 'react'
import DropZone from './DropZone.jsx'
import FileList from './FileList.jsx'

const MODES = {
  imageToPdf: {
    label: 'Image to PDF',
    accept: 'image/png, image/jpeg, image/webp',
    hint: 'images',
    outputExt: 'pdf',
  },
  pdfToWord: {
    label: 'PDF to Word',
    accept: 'application/pdf',
    hint: 'a PDF',
    outputExt: 'docx',
  },
}

let idCounter = 0

export default function Converter() {
  const [mode, setMode] = useState('imageToPdf')
  const [files, setFiles] = useState([])
  const timers = useRef({})

  const config = MODES[mode]

  function switchMode(next) {
    Object.values(timers.current).forEach(clearInterval)
    timers.current = {}
    setMode(next)
    setFiles([])
  }

  function addFiles(incoming) {
    const mapped = incoming.map((file) => ({
      id: ++idCounter,
      name: renameForOutput(file.name, config.outputExt),
      size: file.size,
      status: 'queued',
      progress: 0,
    }))
    setFiles((prev) => [...prev, ...mapped])
  }

  function renameForOutput(name, ext) {
    const base = name.replace(/\.[^/.]+$/, '')
    return `${base}.${ext}`
  }

  function convertAll() {
    setFiles((prev) => prev.map((f) => (f.status === 'queued' ? { ...f, status: 'converting' } : f)))
    setFiles((prevAfterFlag) => {
      prevAfterFlag
        .filter((f) => f.status === 'converting')
        .forEach((f) => runMockConversion(f.id))
      return prevAfterFlag
    })
  }

  function runMockConversion(id) {
    const speed = 6 + Math.random() * 10
    timers.current[id] = setInterval(() => {
      setFiles((prev) =>
        prev.map((f) => {
          if (f.id !== id) return f
          const nextProgress = Math.min(100, f.progress + speed)
          if (nextProgress >= 100) {
            clearInterval(timers.current[id])
            delete timers.current[id]
            return { ...f, progress: 100, status: 'done' }
          }
          return { ...f, progress: nextProgress }
        }),
      )
    }, 180)
  }

  function downloadOne(file) {
    const blob = new Blob(
      [
        `This is a placeholder ${file.name} generated by the Presswork demo.\n\n` +
          `In a production build, this file would contain the real converted output.`,
      ],
      { type: 'text/plain' },
    )
    triggerDownload(blob, file.name.replace(/\.[^/.]+$/, '.txt'))
  }

  function downloadAll() {
    files
      .filter((f) => f.status === 'done')
      .forEach((f, i) => setTimeout(() => downloadOne(f), i * 150))
  }

  function triggerDownload(blob, filename) {
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = filename
    document.body.appendChild(a)
    a.click()
    a.remove()
    URL.revokeObjectURL(url)
  }

  const hasQueued = files.some((f) => f.status === 'queued')

  return (
    <section id="tool" className="border-t border-inkLine">
      <div className="mx-auto max-w-3xl px-6 py-20 md:px-10">
        <h2 className="font-display text-2xl text-cream md:text-3xl">The converter</h2>
        <p className="mt-3 max-w-lg font-sans text-sm text-ash">
          Pick a direction, add your files, and convert. This demo simulates
          the conversion so it can run entirely client-side.
        </p>

        <div className="mt-9 flex gap-8 border-b border-inkLine font-sans text-sm">
          {Object.entries(MODES).map(([key, m]) => (
            <button
              key={key}
              onClick={() => switchMode(key)}
              className={`relative -mb-px pb-3 transition-colors ${
                mode === key ? 'text-cream' : 'text-ash hover:text-cream'
              }`}
            >
              {m.label}
              {mode === key && (
                <span className="absolute inset-x-0 -bottom-px h-[2px] bg-brass" />
              )}
            </button>
          ))}
        </div>

        <div className="mt-8">
          <DropZone accept={config.accept} hint={config.hint} onFiles={addFiles} />

          <FileList
            files={files}
            outputExt={config.outputExt}
            onDownload={downloadOne}
            onDownloadAll={downloadAll}
          />

          {files.length > 0 && hasQueued && (
            <button
              onClick={convertAll}
              className="mt-6 rounded-md bg-brass px-6 py-2.5 font-sans text-sm font-medium text-ink transition-colors hover:bg-brassDark"
            >
              Convert {files.filter((f) => f.status === 'queued').length} file
              {files.filter((f) => f.status === 'queued').length > 1 ? 's' : ''}
            </button>
          )}
        </div>
      </div>
    </section>
  )
}
